version: '3.8'
services:
  hardhat-node:
    build:
      context: .
      dockerfile: Dockerfile.hardhat
    ports:
      - "8545:8545"
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "--post-data='{\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[],\"id\":1}'", "--header='Content-Type: application/json'", "http://localhost:8545" ]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_RPC_URL=http://hardhat-node:8545
    depends_on:
      hardhat-node:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:3000" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
